### ISSUE TITLE
Occasionally stuck in mutex.create(`BASProcess${pid}`);

### ISSUE THREAD

**Issue by dmitryp-rebel** [CheshireCaat/browser-with-fingerprints#16]
Script runs few browsers in parallel. Script occasionally stucks forever in synchronous call mutex.create(`BASProcess${pid}`); I am sure about this point because of added debug message right before and after. It looks like deadlock with mutex. It usually happens after an hours of running. I suspect that issue won't be investigated in any close future due missing code to reproduce issue. So I wonder 

 * Is there any graceful workaround here?
 * May be it is possible to rewrite mutex.create() into async code or add timeout?
 * Is there mutex source code?
 * Can mutex.node be replaced with another library?

**Update:**
 Looks that mutex is created and locked but seemed never released until script is stopped. Windows re-uses same process IDs. And long running script(s) will stuck trying to acquire mutex with re-used PID sooner or later. Multiple scripts affect each other also even if they use different workingFolders/instances because use same mutex namespace.
So proper solution should be to release mutex.

**Comment by dmitryp-rebel** [comment]
Actually, role and meaning of this mutex is not clear.

**Comment by dmitryp-rebel** [comment]
Do workaround testing here: https://github.com/dmitryp-rebel/browser-with-fingerprints/tree/mutex-workaround

**Comment by CheshireCaat** [comment]
Good day, at the moment I’m busy with other tasks, I’ll try to look into the problem, but later.

Previously, there were no problems with this, and there were no changes in this part. Another library is not suitable because the implementation must follow the approach used in the original **BAS** program. I won't go into details of the implementation, but without a mutex the work is impossible.

Your point about reusing process ids doesn't apply here because the **PID** is unique and generated independently at the engine level, not the system level. Anyway, I'll see later how to improve this and avoid possible problems.
